# Generated by Django 4.1.7 on 2023-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.TextField(blank=True),
        ),
    ]
